In [62]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.utils import to_categorical

In [63]:
data = pd.read_csv('lung_cancer_patient_datasets.csv')

In [184]:
data

Patient Id  Age  Gender  Alcohol use  OccuPational Hazards  Genetic Risk  \
0           P1   33       1            4                     4             3   
1          P10   17       1            1                     3             4   
2         P100   35       1            5                     5             5   
3        P1000   37       1            7                     7             6   
4         P101   46       1            8                     7             7   
..         ...  ...     ...          ...                   ...           ...   
995       P995   44       1            7                     7             7   
996       P996   37       2            8                     7             7   
997       P997   25       2            5                     5             5   
998       P998   18       2            8                     7             7   
999       P999   47       1            5                     5             5   

     chronic Lung Disease  Obesity  Smoking  Chest Pain  Coughing of Blood  \
0                       2        4        3           2                  4   
1                       2        2        2           2                  3   
2                       4        7        2           4                  8   
3                       7        7        7           7                  8   
4                       6        7        8           7                  9   
..                    ...      ...      ...         ...                ...   
995                     6        7        7           7                  7   
996                     6        7        7           7                  7   
997                     4        7        2           4                  8   
998                     6        7        8           7                  9   
999                     4        7        2           4                  8   

     Fatigue  Shortness of Breath  Swallowing Difficulty  Dry Cough   Level  
0          3                    2                      3          3     Low  
1          1                    7                      6          7  Medium  
2          8                    9                      1          7    High  
3          4                    3                      4          7    High  
4          3                    4                      4          2    High  
..       ...                  ...                    ...        ...     ...  
995        5                    2                      8          5    High  
996        9                    5                      2          1    High  
997        8                    9                      1          7    High  
998        3                    4                      4          2    High  
999        8                    9                      1          7    High  

[1000 rows x 16 columns]

In [65]:
labels = data['Level']
labels = labels.tolist()

In [66]:
type(labels)

list

In [67]:
labels_num = []
for i in labels:
    if(i == 'Low'):
        labels_num.append(0)
    elif (i == 'Medium'):
        labels_num.append(1)
    else:
        labels_num.append(2)

In [68]:
labels_num = np.array(labels_num)

In [69]:
labels_num.shape

(1000,)

In [145]:
features = data[data.columns[1:15]]

In [146]:
features

Age  Gender  Alcohol use  OccuPational Hazards  Genetic Risk  \
0     33       1            4                     4             3   
1     17       1            1                     3             4   
2     35       1            5                     5             5   
3     37       1            7                     7             6   
4     46       1            8                     7             7   
..   ...     ...          ...                   ...           ...   
995   44       1            7                     7             7   
996   37       2            8                     7             7   
997   25       2            5                     5             5   
998   18       2            8                     7             7   
999   47       1            5                     5             5   

     chronic Lung Disease  Obesity  Smoking  Chest Pain  Coughing of Blood  \
0                       2        4        3           2                  4   
1                       2        2        2           2                  3   
2                       4        7        2           4                  8   
3                       7        7        7           7                  8   
4                       6        7        8           7                  9   
..                    ...      ...      ...         ...                ...   
995                     6        7        7           7                  7   
996                     6        7        7           7                  7   
997                     4        7        2           4                  8   
998                     6        7        8           7                  9   
999                     4        7        2           4                  8   

     Fatigue  Shortness of Breath  Swallowing Difficulty  Dry Cough  
0          3                    2                      3          3  
1          1                    7                      6          7  
2          8                    9                      1          7  
3          4                    3                      4          7  
4          3                    4                      4          2  
..       ...                  ...                    ...        ...  
995        5                    2                      8          5  
996        9                    5                      2          1  
997        8                    9                      1          7  
998        3                    4                      4          2  
999        8                    9                      1          7  

[1000 rows x 14 columns]

In [147]:
type(features)

pandas.core.frame.DataFrame

In [148]:
features= features.values.tolist()

In [149]:
features = np.array(features)

In [150]:
features

array([[33,  1,  4, ...,  2,  3,  3],
       [17,  1,  1, ...,  7,  6,  7],
       [35,  1,  5, ...,  9,  1,  7],
       ...,
       [25,  2,  5, ...,  9,  1,  7],
       [18,  2,  8, ...,  4,  4,  2],
       [47,  1,  5, ...,  9,  1,  7]])

In [151]:
len(labels_num)

1000

In [152]:
len(features)

1000

In [153]:
X = features
y = labels_num

In [154]:
X.shape

(1000, 14)

In [155]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [156]:
y_train = to_categorical(y_train, num_classes=3)

In [157]:
len(X_train)

670

In [158]:
len(X_test)

330

In [159]:
len(y_train)

670

In [160]:
len(y_test)

330

In [161]:
# Normalisasi Data
scaler_object = MinMaxScaler()

In [162]:
scaler_object.fit(X_train)
# Compute the minimum and maximum value of data

C:\Users\lenopo\anaconda3\envs\python-cvcourse\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [163]:
scaler_object

MinMaxScaler(copy=True, feature_range=(0, 1))

In [164]:
scaled_X_train = scaler_object.transform(X_train)

In [165]:
scaled_X_test = scaler_object.transform(X_test)

In [166]:
scaled_X_train.shape

(670, 14)

In [167]:
scaled_X_test.shape

(330, 14)

In [168]:
y_train.shape

(670, 3)

In [169]:
y_test.shape

(330,)

In [170]:
from keras.models import Sequential
from keras.layers import Dense

In [171]:
model = Sequential()

model.add(Dense(14, input_dim=14,activation='relu')) # relu = rectified linear unit

model.add(Dense(26, activation='relu'))

model.add(Dense(3, activation='sigmoid'))

In [172]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [173]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 1.0787 - acc: 0.5328
Epoch 2/50
 - 0s - loss: 1.0214 - acc: 0.6104
Epoch 3/50
 - 0s - loss: 0.9645 - acc: 0.5552
Epoch 4/50
 - 0s - loss: 0.8993 - acc: 0.5612
Epoch 5/50
 - 0s - loss: 0.8269 - acc: 0.6791
Epoch 6/50
 - 0s - loss: 0.7539 - acc: 0.7642
Epoch 7/50
 - 0s - loss: 0.6841 - acc: 0.7866
Epoch 8/50
 - 0s - loss: 0.6198 - acc: 0.7896
Epoch 9/50
 - 0s - loss: 0.5630 - acc: 0.8209
Epoch 10/50
 - 0s - loss: 0.5078 - acc: 0.8388
Epoch 11/50
 - 0s - loss: 0.4568 - acc: 0.8493
Epoch 12/50
 - 0s - loss: 0.4161 - acc: 0.8448
Epoch 13/50
 - 0s - loss: 0.3795 - acc: 0.8642
Epoch 14/50
 - 0s - loss: 0.3505 - acc: 0.8716
Epoch 15/50
 - 0s - loss: 0.3268 - acc: 0.8910
Epoch 16/50
 - 0s - loss: 0.3025 - acc: 0.9015
Epoch 17/50
 - 0s - loss: 0.2853 - acc: 0.9119
Epoch 18/50
 - 0s - loss: 0.2658 - acc: 0.9224
Epoch 19/50
 - 0s - loss: 0.2503 - acc: 0.9388
Epoch 20/50
 - 0s - loss: 0.2334 - acc: 0.9358
Epoch 21/50
 - 0s - loss: 0.2199 - acc: 0.9373
Epoch 22/50
 - 0s - lo

In [174]:
model.predict_classes(scaled_X_test)

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 2, 2, 2, 1,
       0, 1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 1, 2, 0, 2, 2, 1, 1,
       1, 0, 0, 1, 2, 0, 1, 2, 1, 2, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 1,
       2, 2, 1, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 2, 0,
       2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 0, 1,
       0, 2, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 1, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 1, 1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1, 2, 2,
       0, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 2, 2, 1, 1, 0,
       1, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 0,
       0, 2, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 2, 2, 0, 2, 0,
       1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 1, 2, 0, 0, 2,

In [175]:
y_test

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 2, 2, 2, 1,
       0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2, 1, 2, 0, 2, 2, 0, 1,
       1, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 1,
       2, 2, 1, 2, 2, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1, 2, 2, 2, 0,
       2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1,
       0, 2, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 0, 1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1, 2, 2,
       0, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 2, 1, 1, 0,
       1, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 0,
       0, 2, 2, 0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 2, 2, 0, 2, 0,
       1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 0, 0, 2,

In [176]:
model.metrics_names

['loss', 'acc']

In [177]:
from sklearn.metrics import confusion_matrix, classification_report

In [178]:
scaled_X_test.shape

(330, 14)

In [179]:
predictions = model.predict_classes(scaled_X_test)

In [180]:
confusion_matrix(y_test,predictions)

array([[ 79,  17,   0],
       [  0, 106,   0],
       [  0,   0, 128]], dtype=int64)

In [181]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       1.00      0.82      0.90        96
          1       0.86      1.00      0.93       106
          2       1.00      1.00      1.00       128

avg / total       0.96      0.95      0.95       330



In [185]:
model.save('lungCancerClassificationModel.h5')

In [186]:
from keras.models import load_model

In [187]:
newmodel = load_model('lungCancerClassificationModel.h5')

In [188]:
newmodel.predict_classes(scaled_X_test)

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 2, 2, 2, 1,
       0, 1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 1, 2, 0, 2, 2, 1, 1,
       1, 0, 0, 1, 2, 0, 1, 2, 1, 2, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 1,
       2, 2, 1, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 2, 0,
       2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 0, 1,
       0, 2, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 1, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 1, 1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1, 2, 2,
       0, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 2, 2, 1, 1, 0,
       1, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 0,
       0, 2, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 2, 2, 0, 2, 0,
       1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 1, 2, 0, 0, 2,