In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
data = pd.read_csv('lung_cancer_patient_datasets.csv')

In [3]:
data

Patient Id  Age  Gender  Alcohol use  OccuPational Hazards  Genetic Risk  \
0           P1   33       1            4                     4             3   
1          P10   17       1            1                     3             4   
2         P100   35       1            5                     5             5   
3        P1000   37       1            7                     7             6   
4         P101   46       1            8                     7             7   
..         ...  ...     ...          ...                   ...           ...   
995       P995   44       1            7                     7             7   
996       P996   37       2            8                     7             7   
997       P997   25       2            5                     5             5   
998       P998   18       2            8                     7             7   
999       P999   47       1            5                     5             5   

     chronic Lung Disease  Obesity  Smoking  Chest Pain  Coughing of Blood  \
0                       2        4        3           2                  4   
1                       2        2        2           2                  3   
2                       4        7        2           4                  8   
3                       7        7        7           7                  8   
4                       6        7        8           7                  9   
..                    ...      ...      ...         ...                ...   
995                     6        7        7           7                  7   
996                     6        7        7           7                  7   
997                     4        7        2           4                  8   
998                     6        7        8           7                  9   
999                     4        7        2           4                  8   

     Fatigue  Shortness of Breath  Swallowing Difficulty  Dry Cough   Level  
0          3                    2                      3          3     Low  
1          1                    7                      6          7  Medium  
2          8                    9                      1          7    High  
3          4                    3                      4          7    High  
4          3                    4                      4          2    High  
..       ...                  ...                    ...        ...     ...  
995        5                    2                      8          5    High  
996        9                    5                      2          1    High  
997        8                    9                      1          7    High  
998        3                    4                      4          2    High  
999        8                    9                      1          7    High  

[1000 rows x 16 columns]

In [4]:
labels = data['Level']
labels = labels.tolist()

In [6]:
# labels

In [7]:
labels_num = []
for i in labels:
    if(i == 'Low'):
        labels_num.append(0)
    elif (i == 'Medium'):
        labels_num.append(1)
    else:
        labels_num.append(2)

In [8]:
labels_num = np.array(labels_num)

In [10]:
# labels_num

In [11]:
features = data[data.columns[1:15]]

In [12]:
features= features.values.tolist()

In [13]:
features = np.array(features)

In [15]:
# features

In [16]:
X = features
y = labels_num

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [25]:
# y_train

In [26]:
y_train = to_categorical(y_train, num_classes=3)#[[1,0,0], [0,1,0], [0,0,1]]

In [27]:
y_train

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [28]:
# Normalisasi Data
scaler_object = MinMaxScaler()

In [29]:
scaler_object.fit(X_train)
# Compute the minimum and maximum value of data

C:\Users\lenopo\anaconda3\envs\python-cvcourse\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [30]:
scaled_X_train = scaler_object.transform(X_train)

In [31]:
scaled_X_test = scaler_object.transform(X_test)

In [32]:
scaled_X_train

array([[0.23728814, 0.        , 0.85714286, ..., 0.625     , 0.14285714,
        0.16666667],
       [0.52542373, 0.        , 0.85714286, ..., 0.5       , 0.57142857,
        0.83333333],
       [0.6440678 , 0.        , 0.14285714, ..., 0.        , 0.14285714,
        0.33333333],
       ...,
       [0.37288136, 1.        , 0.        , ..., 0.125     , 1.        ,
        0.16666667],
       [0.59322034, 0.        , 0.57142857, ..., 1.        , 0.        ,
        1.        ],
       [0.59322034, 0.        , 0.57142857, ..., 1.        , 0.        ,
        1.        ]])

In [34]:
scaled_X_train.min()

0.0

In [35]:
from keras.models import Sequential
from keras.layers import Dense

In [36]:
model = Sequential()

model.add(Dense(14, input_dim=14,activation='relu')) # relu = rectified linear unit

model.add(Dense(28, activation='relu'))

model.add(Dense(3, activation='sigmoid'))

In [37]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [38]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 1.0801 - acc: 0.5284
Epoch 2/50
 - 0s - loss: 1.0440 - acc: 0.5731
Epoch 3/50
 - 0s - loss: 1.0037 - acc: 0.5836
Epoch 4/50
 - 0s - loss: 0.9491 - acc: 0.5836
Epoch 5/50
 - 0s - loss: 0.8802 - acc: 0.6119
Epoch 6/50
 - 0s - loss: 0.8092 - acc: 0.6194
Epoch 7/50
 - 0s - loss: 0.7400 - acc: 0.6627
Epoch 8/50
 - 0s - loss: 0.6761 - acc: 0.7269
Epoch 9/50
 - 0s - loss: 0.6058 - acc: 0.7806
Epoch 10/50
 - 0s - loss: 0.5378 - acc: 0.8284
Epoch 11/50
 - 0s - loss: 0.4735 - acc: 0.8522
Epoch 12/50
 - 0s - loss: 0.4190 - acc: 0.8627
Epoch 13/50
 - 0s - loss: 0.3722 - acc: 0.8701
Epoch 14/50
 - 0s - loss: 0.3308 - acc: 0.8925
Epoch 15/50
 - 0s - loss: 0.3022 - acc: 0.8940
Epoch 16/50
 - 0s - loss: 0.2727 - acc: 0.9075
Epoch 17/50
 - 0s - loss: 0.2507 - acc: 0.9194
Epoch 18/50
 - 0s - loss: 0.2305 - acc: 0.9209
Epoch 19/50
 - 0s - loss: 0.2165 - acc: 0.9224
Epoch 20/50
 - 0s - loss: 0.1988 - acc: 0.9328
Epoch 21/50
 - 0s - loss: 0.1887 - acc: 0.9478
Epoch 22/50
 - 0s - lo

In [40]:
# model.predict_classes(scaled_X_test)

In [41]:
model.metrics_names

['loss', 'acc']

In [42]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
scaled_X_test.shape

In [43]:
predictions = model.predict_classes(scaled_X_test)

In [44]:
confusion_matrix(y_test,predictions)

array([[ 91,   5,   0],
       [  1, 105,   0],
       [  0,   0, 128]], dtype=int64)

In [45]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.99      0.95      0.97        96
          1       0.95      0.99      0.97       106
          2       1.00      1.00      1.00       128

avg / total       0.98      0.98      0.98       330



In [46]:
model.save('lungCancerClassificationModel.h5')

In [47]:
from keras.models import load_model

In [48]:
newmodel = load_model('lungCancerClassificationModel.h5')

In [49]:
newmodel.predict_classes(scaled_X_test)

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 2, 2, 2, 1,
       0, 1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2, 1, 2, 0, 2, 2, 0, 1,
       1, 0, 0, 1, 2, 0, 1, 2, 1, 2, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 1,
       2, 2, 1, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 2, 0,
       2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1,
       0, 2, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 0, 1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1, 2, 2,
       0, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 2, 1, 1, 0,
       1, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 0,
       0, 2, 2, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 2, 0,
       1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 0, 0, 2,